# Reference: (N/A)

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ceilometer-central-pdb
spec:
  selector:
    matchLabels:
      app: ceilometer-central
  minAvailable: 1
  #maxUnavailable: 2

---

apiVersion: v1
kind: Service
metadata:
  name: ceilometer-central
  labels:
    app: ceilometer-central
spec:
  ports:
  - name: gnocchi-api
    port: 8041
    targetPort: 8041
  #sessionAffinity: ClientIP
  clusterIP: None
  #type: NodePort # Or LoadBalancer in production w/ proper security
  #type: LoadBalancer
  selector:
    app: ceilometer-central

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ceilometer-central
  labels:
    app: ceilometer-central
spec:
  serviceName: "ceilometer-central"
  replicas: 1
  podManagementPolicy: OrderedReady
  #podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: ceilometer-central
  template:
    metadata:
      labels:
        app: ceilometer-central
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: "app"
                 operator: In
                 values:
                 - ceilometer-central
             topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        controller: "true"
      initContainers:
      - name: wait1
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: call518/oaas-init-container:1.0
        envFrom:
          - configMapRef:
              name: env-common
        volumeMounts:
        - name: init-container-scripts
          mountPath: /init-container-scripts
        command: ["/bin/bash","-c","/init-container-scripts/init-check-zookeeper.sh"]
      - name: wait2
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: call518/oaas-init-container:1.0
        envFrom:
          - configMapRef:
              name: env-common
        volumeMounts:
        - name: init-container-scripts
          mountPath: /init-container-scripts
        command: ["/bin/bash","-c","/init-container-scripts/init-check-haproxy.sh"]
      - name: wait3
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: call518/oaas-init-container:1.0
        envFrom:
          - configMapRef:
              name: env-common
        volumeMounts:
        - name: init-container-scripts
          mountPath: /init-container-scripts
        command: ["/bin/bash","-c","/init-container-scripts/init-check-memcached.sh"]
      - name: wait4
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: call518/oaas-init-container:1.0
        envFrom:
          - configMapRef:
              name: env-common
        volumeMounts:
        - name: init-container-scripts
          mountPath: /init-container-scripts
        command: ["/bin/bash","-c","/init-container-scripts/init-check-rabbitmq.sh"]
      - name: wait5
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: call518/oaas-init-container:1.0
        envFrom:
          - configMapRef:
              name: env-common
        volumeMounts:
        - name: init-container-scripts
          mountPath: /init-container-scripts
        command: ["/bin/bash","-c","/init-container-scripts/init-check-keystone.sh"]
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "ceilometer-central"
      #- ip: "192.168.0.150"
      #  hostnames:
      #  - "nfs-server"
      containers:
        - name: ceilometer-central
          image: call518/oaas-ocata:latest
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          #securityContext:
          #  privileged: true
          #  capabilities:
          #    add:
          #    - CAP_SYS_ADMIN
          envFrom:
            - configMapRef:
                name: env-common
          command: ["/scripts/ceilometer-central-init.sh"]
          ports:
            - containerPort: 8041
          volumeMounts:
          - name: openstack-openrc
            mountPath: /root/openrc
          - name: ceilometer-central-setup
            mountPath: /scripts
          - name: pvc-ceilometer-gnocchi
            mountPath: /var/lib/gnocchi
          readinessProbe:
            exec:
              command:
              - /check-init.sh
            initialDelaySeconds: 60
            periodSeconds: 5
            #timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          #livenessProbe:
          #  exec:
          #    command:
          #    - /healthcheck.sh
          #    - --liveness
          #livenessProbe:
          #  tcpSocket:
          #    port: 8041
          #  initialDelaySeconds: 120
          #  periodSeconds: 10
      volumes:
      - name: init-container-scripts
        configMap:
          name: init-container-scripts
          defaultMode: 0755
      - name: ceilometer-central-setup
        configMap:
          name: ceilometer-central-setup
          defaultMode: 0755
      - name: openstack-openrc
        configMap:
          name: openstack-openrc
          defaultMode: 0755
      - name: pvc-ceilometer-gnocchi
        persistentVolumeClaim:
          claimName: pvc-ceilometer-gnocchi
