apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-novncproxy-setup
data:
  nova-novncproxy-init.sh: |
    #!/bin/bash
    set -e;
    cp -a /etc/nova/nova.conf /etc/nova/nova.conf.default
    cat /scripts/nova.conf > /etc/nova/nova.conf
    sed -i "s/___MY_IP___/$MY_POD_IP/g" /etc/nova/nova.conf
    service nova-novncproxy restart
    sleep 5;
    #until (echo $NOVNCPROXY_SERVICES | grep -q "nova-scheduler ${HOSTNAME} enabled up") && (echo $NOVNCPROXY_SERVICES | grep -q "nova-consoleauth ${HOSTNAME} enabled up") && (echo $NOVNCPROXY_SERVICES | grep -q "nova-conductor ${HOSTNAME} enabled up")
    #do
    #  echo "waiting for service response....."
    #  NOVNCPROXY_SERVICES=$(nova service-list | sed -e 's/ //g'| cut -d'|' -f 3,4,6,7 | grep "^nova-" | sed -e 's/|/ /g' || true)
    #  sleep 5
    #done
    #echo "ok~~~~ service is ready~~!!!"
    #nova service-list
    touch /.setup_completed
    tail -F /var/log/syslog /var/log/nova/*

  nova.conf: |
    [DEFAULT]
    daemon = false
    novncproxy_host = 0.0.0.0
    novncproxy_port = 6080
    record = false
    source_is_ipv6 = false
    ssl_only = false
    [api_database]
    [barbican]
    [cache]
    [cells]
    [cinder]
    [cloudpipe]
    [conductor]
    [cors]
    [cors.subdomain]
    [crypto]
    [database]
    [ephemeral_storage_encryption]
    [glance]
    [guestfs]
    [hyperv]
    [image_file_url]
    [ironic]
    [key_manager]
    [keystone_authtoken]
    [libvirt]
    [matchmaker_redis]
    [metrics]
    [mks]
    [neutron]
    [osapi_v21]
    [oslo_concurrency]
    [oslo_messaging_amqp]
    [oslo_messaging_notifications]
    [oslo_messaging_rabbit]
    [oslo_messaging_zmq]
    [oslo_middleware]
    [oslo_policy]
    [placement]
    [placement_database]
    [rdp]
    [remote_debug]
    [scheduler]
    [serial_console]
    [spice]
    [ssl]
    [trusted_computing]
    [upgrade_levels]
    [vmware]
    [vnc]
    enabled = true
    vncserver_listen = 0.0.0.0
    vnc_auto.html vncserver_listen = 0.0.0.0
    vncserver_proxyclient_address = $my_ip
    novncproxy_host = $my_ip
    novncproxy_port = 6080
    novncproxy_base_url = http://192.168.0.151:30068/vnc_auto.html
    [workarounds]
    [wsgi]
    [xenserver]
    [xvp]
