# Reference: (N/A)

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nova-novncproxy-pdb
spec:
  selector:
    matchLabels:
      app: nova-novncproxy
  minAvailable: 1
  #maxUnavailable: 2

---

apiVersion: v1
kind: Service
metadata:
  name: nova-novncproxy
  labels:
    app: nova-novncproxy
spec:
  ports:
  - name: nova-novncproxy
    port: 6080
    targetPort: 6080
    nodePort: 30068
    protocol: TCP
  #sessionAffinity: ClientIP
  clusterIP: None
  #type: NodePort # Or LoadBalancer in production w/ proper security
  #type: LoadBalancer
  selector:
    app: nova-novncproxy

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nova-novncproxy
  labels:
    app: nova-novncproxy
spec:
  serviceName: "nova-novncproxy"
  #replicas: 3
  replicas: 1
  #podManagementPolicy: OrderedReady
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: nova-novncproxy
  template:
    metadata:
      labels:
        app: nova-novncproxy
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: "app"
                 operator: In
                 values:
                 - nova-novncproxy
             topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        novncproxy: "true"
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "nova-novncproxy"
      containers:
        - name: nova-novncproxy
          image: call518/oaas-ocata
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: env-common
          command: ["/scripts/nova-novncproxy-init.sh"]
          ports:
            - containerPort: 6080
          volumeMounts:
          - name: nova-novncproxy-setup
            mountPath: /scripts
          readinessProbe:
            exec:
              command:
              - /check-init.sh
            initialDelaySeconds: 10
            periodSeconds: 5
            #timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
      volumes:
      - name: nova-novncproxy-setup
        configMap:
          name: nova-novncproxy-setup
          defaultMode: 0755
