apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-galera-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: galera
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-galera-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: galera
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-galera-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: galera
      podindex: "2"
