apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-glance-datadir-glance-images
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: pv-glance-datadir-glance-images
