apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-datadir-mongodb-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: mongodb
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-datadir-mongodb-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: mongodb
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-datadir-mongodb-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: mongodb
      podindex: "2"
