apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-datadir-rabbitmq-0
  labels:
    app: rabbitmq
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pods/rabbitmq-0/datadir
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pods/rabbitmq-0/datadir
    server: nfs-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-datadir-rabbitmq-1
  labels:
    app: rabbitmq
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pods/rabbitmq-1/datadir
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pods/rabbitmq-1/datadir
    server: nfs-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-datadir-rabbitmq-2
  labels:
    app: rabbitmq
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pods/rabbitmq-2/datadir
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pods/rabbitmq-2/datadir
    server: nfs-server
