apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-datadir-rabbitmq-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: rabbitmq
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-datadir-rabbitmq-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: rabbitmq
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-datadir-rabbitmq-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: rabbitmq
      podindex: "2"
