apiVersion: v1
kind: Pod
metadata:
 name: sample-pod
spec:
 containers:
 - name: sample-pod
   image: call518/oaas-centos7-systemd
#   ports:
#   - containerPort: 3306
   command:
     - "bash"
     - "-c"
     - |
       tail -F /var/log/messages
