# Reference: https://blog.bluematador.com/posts/running-haproxy-docker-containers-kubernetes/

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: haproxy-pdb
spec:
  selector:
    matchLabels:
      app: haproxy
  minAvailable: 1
  #maxUnavailable: 2

---

apiVersion: v1
kind: Service
metadata:
  name: haproxy-galera
  labels:
    app: haproxy-galera
spec:
  ports:
  - port: 3306
    targetPort: 3306
  #sessionAffinity: ClientIP
  clusterIP: None
  #type: NodePort # Or LoadBalancer in production w/ proper security
  #type: LoadBalancer
  selector:
    app: haproxy

---

apiVersion: v1
kind: Service
metadata:
  name: haproxy-stats
  labels:
    app: haproxy
spec:
  ports:
  - port: 9000
    targetPort: 30090
    nodePort: 30090
    protocol: TCP
  #sessionAffinity: ClientIP
  #clusterIP: None
  type: NodePort # Or LoadBalancer in production w/ proper security
  #type: LoadBalancer
  selector:
    app: haproxy

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: "app"
                 operator: In
                 values:
                 - haproxy
             topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        controller: "true"
      initContainers:
      - name: wait1
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: call518/oaas-init-container:1.0
        envFrom:
          - configMapRef:
              name: env-common
        volumeMounts:
        - name: init-container-scripts
          mountPath: /init-container-scripts
        command: ["/bin/bash", "-c", "/init-container-scripts/init-check-galera.sh"]
      containers:
      - name: haproxy
        image: call518/oaas-haproxy:1.1
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: env-common
        command:
          - bash
          - -c
          - >
            service rsyslog start;
            sed -i "s/@@STATS_USERNAME@@/$K8S_HAPROXY_STATS_USERNAME/g" /etc/haproxy/haproxy.cfg;
            sed -i "s/@@STATS_PASSWORD@@/$K8S_HAPROXY_STATS_PASSWORD/g" /etc/haproxy/haproxy.cfg;
            echo "  server galera-0 galera-0.galera:3306 check inter 2000 rise 2 fall 2 on-marked-down shutdown-sessions" >> /etc/haproxy/haproxy.cfg;
            echo "  server galera-1 galera-1.galera:3306 check inter 2000 rise 2 fall 2 on-marked-down shutdown-sessions backup" >> /etc/haproxy/haproxy.cfg;
            echo "  server galera-2 galera-2.galera:3306 check inter 2000 rise 2 fall 2 on-marked-down shutdown-sessions backup" >> /etc/haproxy/haproxy.cfg;
            haproxy -f /etc/haproxy/haproxy.cfg;
            tail -F /var/log/syslog;
        ports:
          - containerPort: 3306
        ports:
          - containerPort: 9000
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: init-container-scripts
        configMap:
          name: init-container-scripts
          defaultMode: 0755
