apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-mongodb-0
  labels:
    app: mongodb
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /pv/mongodb-0
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /pv/mongodb-0
    server: ___NFS_SERVER_IP___

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-mongodb-1
  labels:
    app: mongodb
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /pv/mongodb-1
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /pv/mongodb-1
    server: ___NFS_SERVER_IP___

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-mongodb-2
  labels:
    app: mongodb
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /pv/mongodb-2
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /pv/mongodb-2
    server: ___NFS_SERVER_IP___
