apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server
  labels:
    app: pv-nfs-server
spec:
  accessModes:
  #- ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 100Gi
  hostPath:
    path: /home/data
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  #persistentVolumeReclaimPolicy: Delete
