apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: pv-nfs-server
