apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zookeeper-zk-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zookeeper-zk-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zookeeper-zk-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "2"
