apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-galera-galera-0
  labels:
    app: galera
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /pv/galera-0
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /pv/galera-0
    server: ___NFS_SERVER_IP___

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-galera-galera-1
  labels:
    app: galera
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /pv/galera-1
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /pv/galera-1
    server: ___NFS_SERVER_IP___

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-galera-galera-2
  labels:
    app: galera
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /pv/galera-2
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /pv/galera-2
    server: ___NFS_SERVER_IP___
