apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-mongodb-0
  labels:
    app: mongodb
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pv/mongodb-0
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pv/mongodb-0
    server: nfs-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-mongodb-1
  labels:
    app: mongodb
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pv/mongodb-1
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pv/mongodb-1
    server: nfs-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-mongodb-2
  labels:
    app: mongodb
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pv/mongodb-2
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pv/mongodb-2
    server: nfs-server
