apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-rabbitmq-0
  labels:
    app: rabbitmq
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pv/rabbitmq-0
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pv/rabbitmq-0
    server: nfs-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-rabbitmq-1
  labels:
    app: rabbitmq
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pv/rabbitmq-1
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pv/rabbitmq-1
    server: nfs-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-rabbitmq-2
  labels:
    app: rabbitmq
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #hostPath:
  #  path: /data/pv/rabbitmq-2
  volumeMode: Filesystem
  #persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pv/rabbitmq-2
    server: nfs-server
